x-common-settings: &common-settings
  networks:
    - test_swarm
  logging:
    driver: "json-file"
    options:
      "max-size": "10m"
      "max-file": "5"

networks:
  test_swarm:
    external: true

services:
  adminer:
    <<: *common-settings
    image: ${LOCAL_REGISTRY}${IMAGES_extra_adminer}
    hostname: adminer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9991:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql1
    deploy:
      mode: replicated
      replicas: 1