services:
  agent:
    image: ${LOCAL_REGISTRY}${IMAGES_extra_agent}
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
        preferences:
          - spread: node.labels.node1

  portainer:
    image: ${LOCAL_REGISTRY}${IMAGES_extra_portainer}
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      # - "9000:9000"
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    networks:
      - agent_network
      - test_swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true
  test_swarm:
    external: true
